### ISSUE TITLE
Could you drop the usage of JavaScript template literals in pattern files?

### ISSUE THREAD

**Issue by krisztianb** [ytiurin/hyphen#10]
Hi there,

thank you for your great library. We are planing to use it in our project.

Would it be possible to drop the usage of JavaScript template literals in the pattern files? Unfortunately Internet Explorer does currently not support them: https://caniuse.com/#feat=template-literals

Thank you.

**Comment by ytiurin** [comment]
Hi krisztianb, I will figure smth out

**Comment by ytiurin** [comment]
Hi @krisztianb, please check v1.1.0

**Comment by krisztianb** [comment]
Hi @ytiurin, thanks a lot.
