### ISSUE TITLE
Problem with minified code in Firefox

### ISSUE THREAD

**Issue by weivall** [ytiurin/hyphen#13]
I have a problem with the minified code in Firefox – <span style="color:red">SyntaxError: invalid range in character class </p>

Minified code (compiled by CRA) has the code ```                              return {
                                        next: function() {
                                            for (var r, i = ""; r = e.charAt(t++);) {
                                                var o = /\s|[\!-\@\[-\`\{-\\xbf]/.test(r),
                                                    a = o ? a === n.readWord ? n.returnWord : n.returnChar : n.readWord;
                                                switch (a) {
                                                    case n.readWord:
                                                        i += r;
                                                        break;
                                                    case n.returnWord:
                                                        return t--, i;
                                                    case n.returnChar:
                                                        return r
                                                }
                                            }
                                            if ("" !== i) return i
                                        }
                                    }``` 
 where 
 ```var o = /\s|[\!-\@\[-\`\{-\\xbf]/.test(r),```
 is wrong expression because of `\\xbbf`. 

Why do we have to escape `¿` sign in 
https://github.com/ytiurin/hyphen/blob/2dbefca8870f27d70ffec551f60afaea4b68dd68/hyphen.js#L100  ?

**Comment by krisztianb** [comment]
It looks like there is already an [open pull request](https://github.com/ytiurin/hyphen/pull/12) for this issue.

**Comment by ytiurin** [comment]
Check version 1.1.1
