### ISSUE TITLE
Classnames are hyphenated, too. 

### ISSUE THREAD

**Issue by FrankConijn** [ytiurin/hyphen#15]
I like the simplicity of your system, but it hyphenates classnames, too. I'd suggest to exclude all attributes, classnames, ids, etc.

**Comment by krisztianb** [comment]
That would take away from the simplicity of the system. :-)

If I understand it correctly you pass HTML to the hyphenation function. That is not how this library should be used.

**Comment by FrankConijn** [comment]
Then what's the use of the system, if I can only have one paragraph hyphenated, and cannot even have a `<span class="essential">essential text</span>` in that paragraph?

**Comment by krisztianb** [comment]
The library is basically not for hyphenation of a HTML page, but for any other application written in JavaScript or TypeScript that needs a hyphenation method.

In my case I use it in a word processing like application and only every pass to it the words at the end of a line that no longer fit into the line.

For your case you could traverse the DOM and pass to it the content of every innerText attribute (not innerHTML!). But there are other libraries that are especially designed to deal with hyphenation on a HTML page. Please take a look at this answer here: https://stackoverflow.com/a/54514561/

**Comment by FrankConijn** [comment]
> The library is basically not for hyphenation of a HTML page, but for any other application written in JavaScript or TypeScript that needs a hyphenation method.

FC: You could've fooled me, with the JS Fiddle example... I guess I'll have to stay with the more complicated systems then. I knew them already but like I said, I liked the simplicity of yours. Thanks for the replies.

**Comment by krisztianb** [comment]
You are right that the example can fool someone into believing that the library should be used to hyphenate HTML. But since it only scans the input string for hyphenation points and insert a specified hyphen character at those point, one should not pass HTML as an input string. Otherwise not only class names but also tag names (eg: section) will get hyphenated.

As said one solution could be to traverse the DOM tree recursively and only every pass text nodes to the hyphenation function. But that needs some tinkering around on ones own and why not use Hyphenopoly.js for this task then, if it was especially created for HTML pages in the first place.

PS: This library is not "mine". I've just contributed one bugfix to the code so far.

**Comment by ytiurin** [comment]
@FrankConijn @krisztianb prevent HTML hyphenation added in v1.3.0

**Comment by krisztianb** [comment]
@ytiurin How does it work? Is it an optional feature?

**Comment by ytiurin** [comment]
@krisztianb same as before but now it skips everything between angle brackers like this `<will not hyphenate>will hyphenate`

**Comment by krisztianb** [comment]
So if I have a very long text and now add `<` at the beginning and `>` at the end, the entire text isn't hyphenated anymore?

Or consider the following text:

    In math we can have operators like x<y and we can also use y>x to define if something is greater or less then.

Would this also deactivate hyphenation for the `<y and we can also use y>` part? :confused: 

Is it possible to deactivate this? This might have unwanted side-effects in the application (a simple word processor) I'm using your library. :cry: 

I really like the simplicity of your library. It has the single purpose of hyphenating text. Removing/ignoring HTML should not be part of the library imho. If somebody has such a problem he/she should use another library to remove HTML first and then use yours to hyphenate.

**Comment by ytiurin** [comment]
@krisztianb sure, I will make it a seperate option with old behavior as default

**Comment by krisztianb** [comment]
@ytiurin Great! Thanks a lot. 👍

**Comment by FrankConijn** [comment]
> 
> 
> @krisztianb sure, I will make it a seperate option with old behavior as default

OK, but how to activate it then? How to use that option?

**Comment by krisztianb** [comment]
@FrankConijn there is an example on the start page (README). You need to use the hyphenation function that has HTML in its name: `hyphenateHTML` or `hyphenateHTMLSync`.

Or if you are using the `createHyphenator` factory function, you must pass `HTML: true` as option. There is also an example for that on the REAME page.

**Comment by FrankConijn** [comment]
You're overestimating my knowledge. With all your answer details, I wonder: how, where? Please take  the (working) JS Fiddle example and tell me where to do what. I know much about HTML and CSS and a couple of things about Javascript, but your answer doesn't help much, unfortunately.

**Comment by krisztianb** [comment]
Ok. Then maybe we should start with a few questions instead. What exactly are you trying to achieve? Where do you want to use the library? Did you follow the installation instructions?

**Comment by FrankConijn** [comment]
I'm getting really tired of this. Your questions are clearly and plainly answered at the beginning of this thread. And in other threads in which you've replied. As you (should) very well know. If you don't want to help me, if you want to keep this a system for just a lucky few, please don't reply. 

Otherwise, please take the JS Fiddle, mentioned in the other thread, as departing point and help me to get it working, including it leaving the HTML tags alone. If you don't want to do that, please stop wasting my and your time. Thank you in advance.

**Comment by krisztianb** [comment]
I know that it is frustrating to get things done when you are not that tech savvy. I'm not the maintainer of the package and I'm also not responsible for how this library is documented. I'm really trying to help you out here. Sorry, that I didn't read the original question. I hope that the answer given here #23 is going to help you. Good luck. :+1:
