### ISSUE TITLE
Example uses wrong language pattern

### ISSUE THREAD

**Issue by ginsterbusch** [ytiurin/hyphen#19]
The example says (and IS written in) German, but the language pattern collection used is for LOWER German = NL = The Netherlands = DUTCH. Yes, those languages are related, but so are English and Dutch. Or Russian and Croatian. Or Spanish and Italian. BUT: They are NOT identical.

cu, w0lf

**Comment by krisztianb** [comment]
Absolutely. The error is in the [JSFiddle](https://jsfiddle.net/ytiurin/ctwwwL0f/).

Unfortunately Eugene doesn't seem to be very active lately. So I guess this won't be fixed anytime soon. :cry:

**Comment by ytiurin** [comment]
Fixed that, sorry for the late reaction! @ginsterbusch
