### ISSUE TITLE
hyphenateHTML will add hyphens to html parameters

### ISSUE THREAD

**Issue by SamuelCharpentier** [ytiurin/hyphen#22]
It seems that if given a string containing HTML, the html tag name will not be hyphenated, but all of its property will.

For example `hyphenateHTMLSync('<span class="user-input" style="text-transform: capitalize;">HTML tags are NOT hyphenated</span>',{hyphenChar: "[-]"})` will return `<span class="user-in[-]put" style="text-trans[-]form: cap[-]i[-]tal[-]ize;">HTML tags are NOT hy[-]phen[-]at[-]ed</span>` leaving the class and other properties broken.

I think it shouldn't. I come to this discovery trying to take the entire innerHTML content of a `<p>`, including some spans with classes, and hyphenate it.

**Comment by FrankConijn** [comment]
See https://github.com/ytiurin/hyphen/issues/15. Not that it's solved, but he just needs to explain how to activate the HTML hyphenation option (which would leave the HTML tags alone).

**Comment by ytiurin** [comment]
@scharpentier0 Thank you for report!
I fixed this bug in [v1.6.2](https://github.com/ytiurin/hyphen/releases/tag/v1.6.2)
Please, check.
