### ISSUE TITLE
Last word not being retrieved

### ISSUE THREAD

**Issue by nicosierra** [ytiurin/hyphen#3]
Your implementation works great, but you forgot to return the word if the string suddenly ends.

For your JS Fiddle example I have set the same strings without the special chars in the end.
You will notice that the last word is removed from the html node.
https://jsfiddle.net/nicosierra/yL1mhbc4/

In the following JS Fiddle you can see that by applying the changes on this PR, you can fix this behaviour. https://jsfiddle.net/nicosierra/eutvdeq8/

**Comment by nicosierra** [comment]
Please check #2

**Comment by ytiurin** [comment]
Thank you
