### ISSUE TITLE
Can I merge Javascript files into one file?

### ISSUE THREAD

**Issue by gusbemacbe** [ytiurin/hyphen#4]
Hello,

Can I merge `hyphen.js` and many Javascript patterns files into one?

Thank you!

Gustavo

**Comment by ytiurin** [comment]
Hi @gusbemacbe,

Technically you can merge many pattern files together, every pattern collection will live in `hyphenationPatterns[Locale_code]` variable, for example `hyphenationPatternsEnGb` or `hyphenationPatternsDe`; or can be imported using AMD or Node import.

``` javascript
var hyphenationPatternsDe = require('patterns/de');
```

Then you initiate your `hyphenate` function with `createHyphenator`

``` javascript
var hyphenate = createHyphenator(hyphenationPatternsDe);
```

**Comment by gusbemacbe** [comment]
I updated to GitHub pages. I copied these codes and pasted into HTML file and it did not work. I also copied the codes from your JSFiddle demo and it did not work either. I do not know why. My template got ugly and I do not know how to fix it. 

Please, check my HTML file:
https://github.com/gusbemacbe/bootstraphyphen/blob/master/teste.html

And to view the page:
https://gusbemacbe.github.io/bootstraphyphen/teste.html

**Comment by ytiurin** [comment]
@gusbemacbe there's a resource loading problem on your demo page, press F12 and check the `Console` tab in your browser

**Comment by gusbemacbe** [comment]
I'm using a Mac and F12 took me to the Dashboard. What is the button in Mac?

**Comment by gusbemacbe** [comment]
I got. Here's the console result. 

![Console Screenshot](https://cloud.githubusercontent.com/assets/2257024/19357535/80e826ae-9148-11e6-9c36-89cdb77c16ae.png)

Do I have to change HTTP to HTTPS?

And how to fix the Github links?

**Comment by ytiurin** [comment]
@gusbemacbe I made a Pull request for your demo page, merge it with your project

**Comment by ytiurin** [comment]
@gusbemacbe in short, you should load files from other origins through https protocol and use root paths './' to load local files

**Comment by gusbemacbe** [comment]
I merged, but the texts disappeared. I thought that with adding of `id= home ka` doesn't work for multiples attributes in an id.

**Comment by ytiurin** [comment]
@gusbemacbe I opened an issue in your project, lets continue conversation there
