### ISSUE TITLE
Trying to get that working in a Vue 3 app

### ISSUE THREAD

**Issue by mamitry** [ytiurin/hyphen#56]
Trying to use this in a Vue 3 app.
But somehow I am only seeing a Promise.

My code can be found in this [repo](https://github.com/mamitry/ytiurin-hyphen-vue-example) and specifically in this [file](https://github.com/mamitry/ytiurin-hyphen-vue-example/blob/main/src/components/HelloWorld.vue).

You can see it running here:
https://codesandbox.io/s/loving-johnson-xxfkm7

**Comment by ohois** [comment]
Your code is wrong. Here is a fixed version:

https://codesandbox.io/s/pensive-liskov-94ryip

**Comment by mamitry** [comment]
Thank You Oliver!
Got it, but hyphenateText is still not being displayed:

[cid:00db6280-8920-4b39-acb9-0ad00c586978]
________________________________
Von: Oliver Hois ***@***.***>
Gesendet: Donnerstag, 30. Juni 2022 17:12
An: ytiurin/hyphen ***@***.***>
Cc: Martin ***@***.***>; Author ***@***.***>
Betreff: Re: [ytiurin/hyphen] Trying to get that working in a Vue 3 app (Issue #56)


Your code is wrong. Here is a fixed version:

https://codesandbox.io/s/pensive-liskov-94ryip<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcodesandbox.io%2Fs%2Fpensive-liskov-94ryip&data=05%7C01%7C%7C4941b2d9810d40495b9a08da5aaae2cb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637921987232727751%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D7ANOzw2Ls6z%2BGK18kr4UUiwcgsqjsviYoTjULEOv8s%3D&reserved=0>

**Comment by mamitry** [comment]
Ok., my bad.   
  
Got it working now:

```javascript
const hyphenateText = ref("");
hyphenate(myText).then((result) => hyphenateText.value = result);
```
