### ISSUE TITLE
Incorrect Output for abortion

### ISSUE THREAD

**Issue by Antix-Development** [ytiurin/hyphen#66]
abortion -> 2io>20 o2n>02 r1ti>010 1tio>100 > -> 0 0 0 0 1 2 0 0 0 -> abor1t2ion -> abor-tion

The word "abortion" however has 3 syllables "a-bor-tion".

**Comment by ytiurin** [comment]
Youre right, however I think patterns for this algorithm were generated from sources, where the word "algorithm" was not hyphenated in that exact place so this case is now hyphenated wrong.
I checked your case on other website https://www.ushuaia.pl/hyphen/?ln=en 
The library is different but tex patterns are same and your case reproduces with "abor-tion" in result

**Comment by krisztianb** [comment]
If I'm not mistaken the algorithm is only around 89% correct when "guessing" the hyphenation points. So there must be a lot of more cases like this.

Can this be fixed by adding the words to the [exception](https://github.com/ytiurin/hyphen/blob/master/patterns/en-us.js#L5010) list?
