### ISSUE TITLE
How make hyphenation in document where multilang words ?

### ISSUE THREAD

**Issue by Nuruddin999** [ytiurin/hyphen#68]
I have document with russian words
i made hypenation in next way using library reactpdf: 
`const hyphenator = hyphen(pattern);
const hyphenationCallback = (word) => {
  return hyphenator(word).split('\u00AD');
}
//
<Text  hyphenationCallback={hyphenationCallback}></Text>
`
But what if i have also english words ? How make hyphenation in document where multilang words, for example englisn and russian ?

**Comment by krisztianb** [comment]
For that you will need to create two different hyphenators. One for English and one for Russian. Then you must hyphenate the English words with the first one and the Russian words with the second one. There is no language detection or anything like that implemented in this library.
