### ISSUE TITLE
Hyphenation error since version 1.7.0

### ISSUE THREAD

**Issue by krisztianb** [ytiurin/hyphen#98]
Hi Yevhen. We are using your great library in our software and recently found a regression after we updated our version.

You can see the error here: https://ytiurin.github.io/hyphen/?path=/story/hyphen-languages--german

* Ge•si•cht should be Ge•sicht
* Kö•ni•gs should be Kö•nigs

As there should always be one vocal in every syllable.

* Example from our document with an error: Grund•schuld•teile should be Grund•schuld•tei•le

This is working in version 1.6.6
No longer working since version 1.7.0

I didn't look at the code specifically but I guess the error was introduced by this commit: https://github.com/ytiurin/hyphen/commit/38ac5771ef7a21ec63ba3a913ee16c194dfbe959

**Comment by ytiurin** [comment]
Hi @krisztianb
I figured out the issue and fixed it in version [1.10.5](https://github.com/ytiurin/hyphen/tree/v1.10.5)
Thank you for report!
I will try to react to further issue reports faster

**Comment by krisztianb** [comment]
Thank you very much. No problem, take your time. This is open source software and we developers also have other things to do.
